<a href="https://colab.research.google.com/github/GrosBoy/DS_intro/blob/homework%2Flesson2-borodinsm/lessons_notebooks/lesson2_borodinsm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import seaborn as sns
import pandas as pd
url="https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
ds=pd.read_csv(url)
print('Loaded dataset')
ds['age_filled']=ds['Age'].fillna(ds['Age'].median())

Loaded dataset

# 1 Задание

In [52]:
ds[['Survived','Name','Pclass','Fare']].sort_values(by='Fare',ascending=False).head(5)

     Survived                                Name  Pclass      Fare
679         1  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
258         1                     Ward, Miss Anna       1  512.3292
737         1              Lesurer, Mr. Gustave J       1  512.3292
88          1           Fortune, Miss Mabel Helen       1  263.0000
438         0                   Fortune, Mr. Mark       1  263.0000

# 2 Задание

In [53]:
print("Кол-во уникальных портов =",ds['Embarked'].nunique())

Кол-во уникальных портов = 3

# 3 Задание

In [54]:
ds['Family_size']=ds['SibSp']+ds['Parch']+1
ds.groupby('Family_size')['Survived'].mean() ## возможно я не так понял задачу

Family_size
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64